%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1      
num_of_cam: 2

imu_topic: "/mavros/imu/data_raw"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/nx/output/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
print_extrinsic: 1   

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-4.9876902235101994e-03, 6.8975396706592029e-03,9.9996377279015758e-01, 0.15,
           -9.9994520639236018e-01, -9.2379465278691342e-03,-4.9238762056141860e-03, 0.025,
           9.2036492313802842e-03, -9.9993353993674983e-01, 6.9432377451592586e-03, -0.03, 
           0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-5.4579099636307138e-03, 9.9270446267020751e-03,9.9993583044303802e-01, 0.15,
           -9.9994301906395133e-01, -9.2282764757631863e-03, -5.3663338096727742e-03, -0.025,
            9.1744124661398141e-03, -9.9990814213019896e-01, 9.9768460765312650e-03, -0.03,
            0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1
use_gpu: 0
use_gpu_acc_flow: 0

#feature traker paprameters
max_cnt: 350            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 1           # perform forward and backward optical flow to improve feature tracking accuracy
remove_outlier: 0
outlier_pixel_threshold: 6

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
mod_num: 2

#imu parameters       The more accurate parameters you provide, the better performance
#acc_n: 0.09          # accelerometer measurement noise standard deviation. #0.2   0.04
#gyr_n: 0.04         # gyroscope measurement noise standard deviation.     #0.05  0.004
#acc_w: 0.02         # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 2.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
#g_norm: 9.79007     # gravity magnitude

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2    #0.2      # accelerometer measurement noise standard deviation. 
gyr_n: 0.05    #0.05      # gyroscope measurement noise standard deviation.     
acc_w: 0.02   #0.02     # accelerometer bias random work noise standard deviation.  
gyr_w: 0.005   #0.003       # gyroscope bias random work noise standard deviation.     
g_norm: 9.8     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.00961936                            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/dji/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

loss_function_type: 0 #0:cauchy, 1:huber
loss_factor: 1
backend_debug_flag: 0
frontend_debug_flag: 0
is_change: 0

#Initial position
initial_pos: [-0, 0.0, 0]

